import { ElementDefinition } from '../types';

export const ENERGY_ELEMENTS: ElementDefinition[] = [
  {
    id: 24,
    key: 'fire',
    name: 'Fire',
    category: 'energy',
    state: 'energy',
    color: [255, 120, 20],
    colorVariance: 25,
    density: -200,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 750,
    heatConductivity: 0.95,
    corrosiveness: 0.1,
    corrosionResistance: 0.9,
    electricalConductivity: 0.2,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 35,
    description: 'Hot thermal energy plasma. Ignites combustibles, melts solids, and emits smoke.',
  },
  {
    id: 31,
    key: 'plasma',
    name: 'Plasma',
    category: 'energy',
    state: 'energy',
    color: [210, 80, 255],
    colorVariance: 20,
    density: -500,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 3500,
    heatConductivity: 1.0,
    corrosiveness: 0.8,
    corrosionResistance: 0.99,
    electricalConductivity: 1.0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 25,
    description: 'Ionized superheated gas state. Obliterates matter, conducts high-voltage current.',
  },
  {
    id: 36,
    key: 'electricity',
    name: 'Electricity',
    category: 'energy',
    state: 'energy',
    color: [120, 230, 255],
    colorVariance: 15,
    density: -9999,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 400,
    heatConductivity: 0.9,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 1.0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 5,
    description: 'Electrical charge flow. Zips rapidly through conductors like metals and salt water.',
  },
  {
    id: 37,
    key: 'spark',
    name: 'Spark',
    category: 'energy',
    state: 'energy',
    color: [255, 240, 110],
    colorVariance: 20,
    density: -150,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 900,
    heatConductivity: 0.9,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0.4,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 14,
    description: 'High-energy incandescent ember. Ignites flammable gases and powders on contact.',
  },
  {
    id: 50,
    key: 'laser',
    name: 'Laser',
    category: 'energy',
    state: 'energy',
    color: [255, 40, 90],
    colorVariance: 10,
    density: -9999,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 2200,
    heatConductivity: 1.0,
    corrosiveness: 0.7,
    corrosionResistance: 1.0,
    electricalConductivity: 0.8,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 10,
    description: 'Coherent concentrated photonic beam. Pierces structures with focused thermal energy.',
  },
];
