import { ElementDefinition } from '../types';

export const GAS_ELEMENTS: ElementDefinition[] = [
  {
    id: 0,
    key: 'air',
    name: 'Air',
    category: 'gas',
    state: 'gas',
    color: [15, 17, 26],
    colorVariance: 0,
    density: 0,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.05,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Empty space. Allows particles to move and gases to diffuse.',
  },
  {
    id: 25,
    key: 'smoke',
    name: 'Smoke',
    category: 'gas',
    state: 'gas',
    color: [95, 95, 105],
    colorVariance: 10,
    density: -50,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 80,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 140,
    description: 'Rising combustion byproduct. Drifts upward and dissipates into open air.',
  },
  {
    id: 32,
    key: 'steam',
    name: 'Steam',
    category: 'gas',
    state: 'gas',
    color: [200, 215, 235],
    colorVariance: 8,
    density: -100,
    viscosity: 1,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 110,
    heatConductivity: 0.4,
    corrosiveness: 0,
    corrosionResistance: 0.95,
    electricalConductivity: 0.05,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: 95,
    freezeProduct: 'water',
    life: 180,
    description: 'Vaporized water gas. Rises swiftly, condenses back into liquid water when cooled.',
  },
  {
    id: 46,
    key: 'toxic_gas',
    name: 'Toxic Gas',
    category: 'gas',
    state: 'gas',
    color: [110, 205, 70],
    colorVariance: 10,
    density: -30,
    viscosity: 1,
    flammability: 0.2,
    burnTemp: 350,
    defaultTemp: 35,
    heatConductivity: 0.1,
    corrosiveness: 0.5,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 200,
    description: 'Noxious chemical vapor. Lethal to biological lifeforms and plants on contact.',
  },
  {
    id: 47,
    key: 'hydrogen',
    name: 'Hydrogen',
    category: 'gas',
    state: 'gas',
    color: [160, 200, 255],
    colorVariance: 8,
    density: -300,
    viscosity: 1,
    flammability: 0.98,
    burnTemp: 80,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Lightest buoyant elemental gas. Extremely combustible in presence of oxygen.',
  },
  {
    id: 48,
    key: 'oxygen',
    name: 'Oxygen',
    category: 'gas',
    state: 'gas',
    color: [180, 225, 255],
    colorVariance: 6,
    density: -80,
    viscosity: 1,
    flammability: 0.1,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Atmospheric oxidant gas. Dramatically accelerates fire and explosion velocity.',
  },
  {
    id: 49,
    key: 'methane',
    name: 'Methane',
    category: 'gas',
    state: 'gas',
    color: [140, 185, 170],
    colorVariance: 8,
    density: -180,
    viscosity: 1,
    flammability: 0.95,
    burnTemp: 100,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Flammable hydrocarbon gas. Produces hot blue combustion flames.',
  },
];
