import { ElementDefinition } from '../types';

export const LIFE_ELEMENTS: ElementDefinition[] = [
  {
    id: 51,
    key: 'plant',
    name: 'Plant',
    category: 'life',
    state: 'solid',
    color: [50, 175, 60],
    colorVariance: 14,
    density: 900,
    viscosity: 0,
    flammability: 0.7,
    burnTemp: 220,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.4,
    electricalConductivity: 0.1,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: -5,
    freezeProduct: null,
    life: 0,
    description: 'Living foliage. Grows when in contact with water and sunlight; flammable.',
  },
  {
    id: 52,
    key: 'vine',
    name: 'Vine',
    category: 'life',
    state: 'solid',
    color: [40, 140, 50],
    colorVariance: 12,
    density: 920,
    viscosity: 0,
    flammability: 0.65,
    burnTemp: 230,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.4,
    electricalConductivity: 0.1,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: -5,
    freezeProduct: null,
    life: 0,
    description: 'Creeping plant structure. Climbs across walls and ceilings.',
  },
  {
    id: 53,
    key: 'fungus',
    name: 'Fungus',
    category: 'life',
    state: 'solid',
    color: [165, 120, 180],
    colorVariance: 14,
    density: 850,
    viscosity: 0,
    flammability: 0.5,
    burnTemp: 180,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0.3,
    corrosionResistance: 0.5,
    electricalConductivity: 0.05,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: -10,
    freezeProduct: null,
    life: 0,
    description: 'Decomposing spore network. Spreads rapidly across organic wood and plant matter.',
  },
  {
    id: 54,
    key: 'seed',
    name: 'Seed',
    category: 'life',
    state: 'powder',
    color: [140, 160, 60],
    colorVariance: 10,
    density: 1100,
    viscosity: 0,
    flammability: 0.6,
    burnTemp: 200,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.6,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Plant embryo powder. Sprouts into lush greenery when nourished with water and soil.',
  },
];
