import { ElementDefinition } from '../types';

export const LIQUID_ELEMENTS: ElementDefinition[] = [
  {
    id: 10,
    key: 'water',
    name: 'Water',
    category: 'liquid',
    state: 'liquid',
    color: [45, 125, 230],
    colorVariance: 8,
    density: 1000,
    viscosity: 5,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 20,
    heatConductivity: 0.6,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0.1,
    boilingPoint: 100,
    boilProduct: 'steam',
    freezingPoint: 0,
    freezeProduct: 'snow',
    life: 0,
    description: 'Essential fluid solvent. Cools hot materials, boils into steam, freezes into ice.',
  },
  {
    id: 11,
    key: 'oil',
    name: 'Oil',
    category: 'liquid',
    state: 'liquid',
    color: [160, 140, 50],
    colorVariance: 10,
    density: 820,
    viscosity: 3,
    flammability: 0.9,
    burnTemp: 120,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: 280,
    boilProduct: 'smoke',
    freezingPoint: -20,
    freezeProduct: null,
    life: 0,
    description: 'Combustible hydrocarbon oil. Floats on water, catches fire readily.',
  },
  {
    id: 21,
    key: 'acid',
    name: 'Acid',
    category: 'liquid',
    state: 'liquid',
    color: [85, 240, 55],
    colorVariance: 12,
    density: 1250,
    viscosity: 4,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.3,
    corrosiveness: 0.95,
    corrosionResistance: 0.99,
    electricalConductivity: 0.6,
    boilingPoint: 115,
    boilProduct: 'toxic_gas',
    freezingPoint: -15,
    freezeProduct: null,
    life: 0,
    description: 'Highly reactive corrosive acid. Dissolves metals, powders, and organic tissue.',
  },
  {
    id: 22,
    key: 'lava',
    name: 'Lava',
    category: 'liquid',
    state: 'liquid',
    color: [255, 90, 20],
    colorVariance: 15,
    density: 3100,
    viscosity: 2,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 1200,
    heatConductivity: 0.85,
    corrosiveness: 0.2,
    corrosionResistance: 0.95,
    electricalConductivity: 0.4,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: 700,
    freezeProduct: 'stone',
    life: 0,
    description: 'Superheated molten rock. Ignites nearby combustibles; cools into stone or obsidian.',
  },
  {
    id: 23,
    key: 'nitro',
    name: 'Nitroglycerin',
    category: 'liquid',
    state: 'liquid',
    color: [90, 195, 140],
    colorVariance: 8,
    density: 1600,
    viscosity: 4,
    flammability: 0.99,
    burnTemp: 60,
    defaultTemp: 18,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.7,
    electricalConductivity: 0.05,
    boilingPoint: 160,
    boilProduct: 'fire_gas',
    freezingPoint: 13,
    freezeProduct: null,
    life: 0,
    description: 'Ultra-sensitive explosive liquid. Shock, pressure, or gentle heat triggers a blast.',
  },
  {
    id: 27,
    key: 'salt_water',
    name: 'Salt Water',
    category: 'liquid',
    state: 'liquid',
    color: [60, 155, 240],
    colorVariance: 8,
    density: 1030,
    viscosity: 5,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 20,
    heatConductivity: 0.65,
    corrosiveness: 0.2,
    corrosionResistance: 0.8,
    electricalConductivity: 0.85,
    boilingPoint: 104,
    boilProduct: 'steam',
    freezingPoint: -2,
    freezeProduct: 'snow',
    life: 0,
    description: 'Saline electrolytic fluid. Superior electrical conductivity, corrosive to iron.',
  },
  {
    id: 28,
    key: 'alcohol',
    name: 'Alcohol',
    category: 'liquid',
    state: 'liquid',
    color: [180, 215, 230],
    colorVariance: 6,
    density: 789,
    viscosity: 6,
    flammability: 0.85,
    burnTemp: 78,
    defaultTemp: 20,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: 78,
    boilProduct: 'fire_gas',
    freezingPoint: -114,
    freezeProduct: null,
    life: 0,
    description: 'Volatile liquid fuel. Burns with a clean low-smoke flame.',
  },
  {
    id: 29,
    key: 'mercury',
    name: 'Mercury',
    category: 'liquid',
    state: 'liquid',
    color: [190, 195, 205],
    colorVariance: 5,
    density: 13534,
    viscosity: 5,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 20,
    heatConductivity: 0.75,
    corrosiveness: 0.1,
    corrosionResistance: 0.95,
    electricalConductivity: 0.9,
    boilingPoint: 356,
    boilProduct: 'toxic_gas',
    freezingPoint: -39,
    freezeProduct: 'metal',
    life: 0,
    description: 'Super-dense liquid metal. Excellent electrical conductor; sinks below all other liquids.',
  },
  {
    id: 33,
    key: 'liquid_nitrogen',
    name: 'Liquid Nitrogen',
    category: 'liquid',
    state: 'liquid',
    color: [130, 220, 255],
    colorVariance: 8,
    density: 808,
    viscosity: 6,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: -196,
    heatConductivity: 0.9,
    corrosiveness: 0,
    corrosionResistance: 0.95,
    electricalConductivity: 0,
    boilingPoint: -195,
    boilProduct: 'air',
    freezingPoint: -210,
    freezeProduct: null,
    life: 0,
    description: 'Cryogenic refrigerant liquid. Instantly freezes nearby liquids and solids on contact.',
  },
];
