import { ElementDefinition } from '../types';

export const POWDER_ELEMENTS: ElementDefinition[] = [
  {
    id: 6,
    key: 'sand',
    name: 'Sand',
    category: 'powder',
    state: 'powder',
    color: [225, 195, 120],
    colorVariance: 15,
    density: 1600,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: 1700,
    boilProduct: 'glass',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Fine granular silica. Falls and piles into natural slopes. Melts into glass.',
  },
  {
    id: 7,
    key: 'dirt',
    name: 'Dirt',
    category: 'powder',
    state: 'powder',
    color: [120, 85, 55],
    colorVariance: 12,
    density: 1400,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.7,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Fertile soil. Nutritious foundation for vegetation and organic growth.',
  },
  {
    id: 8,
    key: 'gunpowder',
    name: 'Gunpowder',
    category: 'powder',
    state: 'powder',
    color: [85, 85, 90],
    colorVariance: 10,
    density: 1300,
    viscosity: 0,
    flammability: 0.95,
    burnTemp: 180,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.5,
    electricalConductivity: 0.1,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Volatile explosive powder. Detonates violently with sparks or high heat.',
  },
  {
    id: 9,
    key: 'salt',
    name: 'Salt',
    category: 'powder',
    state: 'powder',
    color: [240, 240, 245],
    colorVariance: 8,
    density: 2160,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: 1465,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Crystalline mineral salt. Dissolves in water to form conductive salt water.',
  },
  {
    id: 12,
    key: 'sawdust',
    name: 'Sawdust',
    category: 'powder',
    state: 'powder',
    color: [210, 165, 105],
    colorVariance: 14,
    density: 450,
    viscosity: 0,
    flammability: 0.85,
    burnTemp: 200,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.4,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Dry pulverized wood grains. Highly flammable, floats on water.',
  },
  {
    id: 13,
    key: 'sugar',
    name: 'Sugar',
    category: 'powder',
    state: 'powder',
    color: [248, 245, 235],
    colorVariance: 6,
    density: 1590,
    viscosity: 0,
    flammability: 0.5,
    burnTemp: 186,
    defaultTemp: 22,
    heatConductivity: 0.12,
    corrosiveness: 0,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: 200,
    boilProduct: 'smoke',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Granulated carbohydrate. Caramelizes and smokes when heated.',
  },
  {
    id: 14,
    key: 'snow',
    name: 'Snow',
    category: 'powder',
    state: 'powder',
    color: [230, 240, 255],
    colorVariance: 8,
    density: 300,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: -5,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: 1,
    boilProduct: 'water',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Precipitated crystalline ice. Melts swiftly into water above 0 C.',
  },
  {
    id: 15,
    key: 'flour',
    name: 'Flour',
    category: 'powder',
    state: 'powder',
    color: [245, 240, 220],
    colorVariance: 6,
    density: 600,
    viscosity: 0,
    flammability: 0.7,
    burnTemp: 240,
    defaultTemp: 22,
    heatConductivity: 0.08,
    corrosiveness: 0,
    corrosionResistance: 0.7,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Finely milled grain starch. Can ignite into a combustible dust cloud.',
  },
  {
    id: 26,
    key: 'ash',
    name: 'Ash',
    category: 'powder',
    state: 'powder',
    color: [140, 138, 142],
    colorVariance: 10,
    density: 800,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 45,
    heatConductivity: 0.08,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Combustion residue powder. Inert mineral particulate.',
  },
  {
    id: 34,
    key: 'yeast',
    name: 'Yeast',
    category: 'powder',
    state: 'powder',
    color: [215, 195, 150],
    colorVariance: 8,
    density: 750,
    viscosity: 0,
    flammability: 0.3,
    burnTemp: 120,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.6,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Biological micro-organism. Ferments sugar into alcohol and carbon dioxide.',
  },
  {
    id: 35,
    key: 'ant',
    name: 'Ant',
    category: 'powder',
    state: 'powder',
    color: [160, 45, 30],
    colorVariance: 10,
    density: 1200,
    viscosity: 0,
    flammability: 0.4,
    burnTemp: 80,
    defaultTemp: 24,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.4,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: 0,
    freezeProduct: null,
    life: 0,
    description: 'Autonomous digging insect. Tunnels through dirt and wood, building subterranean nests.',
  },
];
