import { ElementDefinition } from '../types';

export const SOLID_ELEMENTS: ElementDefinition[] = [
  {
    id: 1,
    key: 'wall',
    name: 'Wall',
    category: 'solid',
    state: 'solid',
    color: [120, 126, 137],
    colorVariance: 8,
    density: 99999,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Indestructible static barrier. Impermeable to fluids, heat, and chemicals.',
  },
  {
    id: 2,
    key: 'wood',
    name: 'Wood',
    category: 'solid',
    state: 'solid',
    color: [142, 85, 43],
    colorVariance: 12,
    density: 700,
    viscosity: 0,
    flammability: 0.6,
    burnTemp: 260,
    defaultTemp: 22,
    heatConductivity: 0.15,
    corrosiveness: 0,
    corrosionResistance: 0.3,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Organic solid fuel. Ignites at high temperature to produce ash and smoke.',
  },
  {
    id: 3,
    key: 'glass',
    name: 'Glass',
    category: 'solid',
    state: 'solid',
    color: [195, 225, 235],
    colorVariance: 6,
    density: 2500,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.95,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Transparent mineral barrier. Resistant to corrosion, melts at extreme temperatures.',
  },
  {
    id: 4,
    key: 'stone',
    name: 'Stone',
    category: 'solid',
    state: 'solid',
    color: [110, 115, 120],
    colorVariance: 10,
    density: 2700,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.25,
    corrosiveness: 0,
    corrosionResistance: 0.8,
    electricalConductivity: 0,
    boilingPoint: 1150,
    boilProduct: 'lava',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Dense natural rock. Melts into molten lava at extreme temperatures.',
  },
  {
    id: 5,
    key: 'brick',
    name: 'Brick',
    category: 'solid',
    state: 'solid',
    color: [180, 75, 60],
    colorVariance: 10,
    density: 2000,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.7,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Fired clay building block. Thermally stable masonry material.',
  },
  {
    id: 16,
    key: 'wax',
    name: 'Wax',
    category: 'solid',
    state: 'solid',
    color: [240, 235, 210],
    colorVariance: 8,
    density: 900,
    viscosity: 0,
    flammability: 0.4,
    burnTemp: 220,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.85,
    electricalConductivity: 0,
    boilingPoint: 65,
    boilProduct: 'oil',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Low-melting hydrocarbon solid. Melts into flammable liquid oil when heated above 65°C.',
  },
  {
    id: 17,
    key: 'metal',
    name: 'Metal',
    category: 'solid',
    state: 'solid',
    color: [140, 150, 165],
    colorVariance: 8,
    density: 7800,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.8,
    corrosiveness: 0,
    corrosionResistance: 0.2,
    electricalConductivity: 0.9,
    boilingPoint: 1450,
    boilProduct: 'lava',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Ferrous structural metal. Conducts electricity and heat; melts into lava at 1450°C.',
  },
  {
    id: 18,
    key: 'gold',
    name: 'Gold',
    category: 'solid',
    state: 'solid',
    color: [245, 195, 45],
    colorVariance: 8,
    density: 19300,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.9,
    corrosiveness: 0,
    corrosionResistance: 0.99,
    electricalConductivity: 0.95,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Noble heavy metal. Superb electrical conductor, completely immune to corrosion.',
  },
  {
    id: 19,
    key: 'copper',
    name: 'Copper',
    category: 'solid',
    state: 'solid',
    color: [210, 115, 65],
    colorVariance: 8,
    density: 8960,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.95,
    corrosiveness: 0,
    corrosionResistance: 0.4,
    electricalConductivity: 0.98,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'High conductivity transition metal. Ideal for electronic routing.',
  },
  {
    id: 20,
    key: 'rust',
    name: 'Rust',
    category: 'solid',
    state: 'solid',
    color: [160, 70, 35],
    colorVariance: 10,
    density: 5200,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.5,
    electricalConductivity: 0.05,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Corroded iron oxide. Brittle non-conductive solid byproduct.',
  },
  {
    id: 30,
    key: 'rubber',
    name: 'Rubber',
    category: 'solid',
    state: 'solid',
    color: [45, 45, 50],
    colorVariance: 5,
    density: 1100,
    viscosity: 0,
    flammability: 0.3,
    burnTemp: 350,
    defaultTemp: 22,
    heatConductivity: 0.05,
    corrosiveness: 0,
    corrosionResistance: 0.9,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Electrical and thermal insulator. Impermeable to current and fluids.',
  },
  {
    id: 44,
    key: 'obsidian',
    name: 'Obsidian',
    category: 'solid',
    state: 'solid',
    color: [35, 30, 42],
    colorVariance: 6,
    density: 2600,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.1,
    corrosiveness: 0,
    corrosionResistance: 0.98,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Volcanic glass forged by rapid lava cooling. Extremely tough.',
  },
  {
    id: 45,
    key: 'concrete',
    name: 'Concrete',
    category: 'solid',
    state: 'solid',
    color: [145, 148, 150],
    colorVariance: 8,
    density: 2400,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 0.6,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Hydraulic mineral compound. High compressive strength barrier.',
  },
  {
    id: 55,
    key: 'ice',
    name: 'Ice',
    category: 'solid',
    state: 'solid',
    color: [180, 220, 255],
    colorVariance: 8,
    density: 917,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: -5,
    heatConductivity: 0.5,
    corrosiveness: 0,
    corrosionResistance: 0.95,
    electricalConductivity: 0.05,
    boilingPoint: 1,
    boilProduct: 'water',
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Solid crystalline frozen water. Melts rapidly into liquid water above 0°C.',
  },
];
