import { ElementDefinition } from '../types';

export const TOOL_ELEMENTS: ElementDefinition[] = [
  {
    id: 38,
    key: 'uranium',
    name: 'Uranium',
    category: 'special',
    state: 'solid',
    color: [60, 210, 80],
    colorVariance: 15,
    density: 19100,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 250,
    heatConductivity: 0.4,
    corrosiveness: 0.1,
    corrosionResistance: 0.9,
    electricalConductivity: 0.5,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Radioactive fissile isotope. Generates constant heat, prone to runaway reaction.',
  },
  {
    id: 39,
    key: 'heater',
    name: 'Heater',
    category: 'special',
    state: 'solid',
    color: [240, 60, 40],
    colorVariance: 8,
    density: 99999,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 500,
    heatConductivity: 0.95,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0.8,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Constant thermal furnace source. Maintained permanently at 500 C.',
  },
  {
    id: 40,
    key: 'cooler',
    name: 'Cooler',
    category: 'special',
    state: 'solid',
    color: [40, 150, 240],
    colorVariance: 8,
    density: 99999,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: -150,
    heatConductivity: 0.95,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0.8,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Cryogenic cold sink node. Maintained permanently at -150 C.',
  },
  {
    id: 41,
    key: 'eraser',
    name: 'Eraser',
    category: 'special',
    state: 'solid',
    color: [255, 100, 150],
    colorVariance: 0,
    density: 0,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Tool to delete particles and reset cells back to ambient vacuum space.',
  },
  {
    id: 42,
    key: 'clone',
    name: 'Clone',
    category: 'special',
    state: 'solid',
    color: [225, 215, 60],
    colorVariance: 10,
    density: 99999,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0.2,
    corrosiveness: 0,
    corrosionResistance: 1,
    electricalConductivity: 0.3,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Replicator node. Duplicates any adjacent particle into neighboring open cells.',
  },
  {
    id: 43,
    key: 'void',
    name: 'Void',
    category: 'special',
    state: 'solid',
    color: [80, 20, 110],
    colorVariance: 6,
    density: 99999,
    viscosity: 0,
    flammability: 0,
    burnTemp: 9999,
    defaultTemp: 22,
    heatConductivity: 0,
    corrosiveness: 1.0,
    corrosionResistance: 1,
    electricalConductivity: 0,
    boilingPoint: null,
    boilProduct: null,
    freezingPoint: null,
    freezeProduct: null,
    life: 0,
    description: 'Black hole sink. Absorbs and annihilates all matter, fluids, and thermal energy.',
  },
];
