import { ChemicalReaction } from '../types';

export const COMBUSTION_REACTIONS: ChemicalReaction[] = [
  {
    id: 'rx_fire_oil',
    reactantA: 'fire',
    reactantB: 'oil',
    resultA: 'fire',
    resultB: 'fire',
    chance: 0.75,
    heatDelta: 80,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Oil rapidly catches fire, producing thick black smoke plumes.',
  },
  {
    id: 'rx_fire_gunpowder',
    reactantA: 'fire',
    reactantB: 'gunpowder',
    resultA: 'fire',
    resultB: 'spark',
    chance: 0.95,
    heatDelta: 250,
    pressureDelta: 8,
    effect: 'explode',
    description: 'Gunpowder violently deflagrates with explosive shockwave.',
  },
  {
    id: 'rx_spark_gunpowder',
    reactantA: 'spark',
    reactantB: 'gunpowder',
    resultA: 'fire',
    resultB: 'spark',
    chance: 0.98,
    heatDelta: 280,
    pressureDelta: 9,
    effect: 'explode',
    description: 'A stray ember detonates gunpowder.',
  },
  {
    id: 'rx_fire_nitro',
    reactantA: 'fire',
    reactantB: 'nitro',
    resultA: 'fire',
    resultB: 'plasma',
    chance: 1.0,
    heatDelta: 600,
    pressureDelta: 10,
    effect: 'explode',
    description: 'Nitroglycerin violently detonates with massive pressure shockwave.',
  },
  {
    id: 'rx_spark_nitro',
    reactantA: 'spark',
    reactantB: 'nitro',
    resultA: 'fire',
    resultB: 'plasma',
    chance: 1.0,
    heatDelta: 600,
    pressureDelta: 10,
    effect: 'explode',
    description: 'Nitroglycerin shock detonation triggered by electrical spark.',
  },
  {
    id: 'rx_fire_alcohol',
    reactantA: 'fire',
    reactantB: 'alcohol',
    resultA: 'fire',
    resultB: 'fire',
    chance: 0.8,
    heatDelta: 70,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Alcohol burns cleanly with high vapor heat.',
  },
  {
    id: 'rx_fire_wood',
    reactantA: 'fire',
    reactantB: 'wood',
    resultA: 'fire',
    resultB: 'ash',
    chance: 0.3,
    heatDelta: 50,
    pressureDelta: 1,
    effect: 'spark',
    description: 'Wood burns into glowing fire and leaves behind ash residue.',
  },
  {
    id: 'rx_fire_sawdust',
    reactantA: 'fire',
    reactantB: 'sawdust',
    resultA: 'fire',
    resultB: 'smoke',
    chance: 0.75,
    heatDelta: 60,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Suspended sawdust burns rapidly like dust flare.',
  },
  {
    id: 'rx_fire_methane',
    reactantA: 'fire',
    reactantB: 'methane',
    resultA: 'fire',
    resultB: 'smoke',
    chance: 0.9,
    heatDelta: 150,
    pressureDelta: 6,
    effect: 'explode',
    description: 'Methane gas combusts in a fiery airborne flare.',
  },
  {
    id: 'rx_fire_hydrogen',
    reactantA: 'fire',
    reactantB: 'hydrogen',
    resultA: 'steam',
    resultB: 'fire',
    chance: 0.95,
    heatDelta: 220,
    pressureDelta: 7,
    effect: 'explode',
    description: 'Hydrogen reacts explosively with fire, yielding hot water vapor.',
  },
  {
    id: 'rx_hydrogen_oxygen',
    reactantA: 'hydrogen',
    reactantB: 'oxygen',
    resultA: 'steam',
    resultB: 'spark',
    chance: 0.5,
    heatDelta: 350,
    pressureDelta: 8,
    effect: 'explode',
    description: 'Oxy-hydrogen detonation mixture yielding hot steam and sparks.',
  },
  {
    id: 'rx_fire_oxygen',
    reactantA: 'fire',
    reactantB: 'oxygen',
    resultA: 'fire',
    resultB: 'spark',
    chance: 0.85,
    heatDelta: 240,
    pressureDelta: 4,
    effect: 'flash',
    description: 'Atmospheric oxygen accelerates and superheats the combustion flame.',
  },
];
