import { ChemicalReaction } from '../types';

export const CORROSION_REACTIONS: ChemicalReaction[] = [
  {
    id: 'rx_acid_metal',
    reactantA: 'acid',
    reactantB: 'metal',
    resultA: 'hydrogen',
    resultB: 'toxic_gas',
    chance: 0.35,
    heatDelta: 60,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Acid dissolves metal, releasing combustible hydrogen gas and toxic fumes.',
  },
  {
    id: 'rx_acid_wood',
    reactantA: 'acid',
    reactantB: 'wood',
    resultA: 'toxic_gas',
    resultB: 'sawdust',
    chance: 0.4,
    heatDelta: 30,
    pressureDelta: 1,
    effect: 'dissolve',
    description: 'Acid hydrolyzes wood fibers into sawdust and fumes.',
  },
  {
    id: 'rx_acid_plant',
    reactantA: 'acid',
    reactantB: 'plant',
    resultA: 'toxic_gas',
    resultB: null,
    chance: 0.6,
    heatDelta: 20,
    pressureDelta: 0,
    effect: 'dissolve',
    description: 'Acid destroys vegetation, turning organic tissues into noxious gas.',
  },
  {
    id: 'rx_acid_dirt',
    reactantA: 'acid',
    reactantB: 'dirt',
    resultA: 'toxic_gas',
    resultB: null,
    chance: 0.3,
    heatDelta: 15,
    pressureDelta: 0,
    effect: 'dissolve',
    description: 'Acid dissolves mineral soil into gas.',
  },
  {
    id: 'rx_rust_metal_fire',
    reactantA: 'rust',
    reactantB: 'metal',
    resultA: 'lava',
    resultB: 'spark',
    chance: 0.35,
    heatDelta: 700,
    pressureDelta: 4,
    effect: 'flash',
    description: 'Thermite reaction: rust and metal generate extreme molten iron lava.',
  },
  {
    id: 'rx_sand_lava',
    reactantA: 'sand',
    reactantB: 'lava',
    resultA: 'glass',
    resultB: 'lava',
    chance: 0.4,
    heatDelta: 50,
    pressureDelta: 0,
    effect: 'flash',
    description: 'Intense lava heat vitrifies quartz sand into solid glass.',
  },
];
