import { ChemicalReaction } from '../types';

export const CRYO_NUCLEAR_REACTIONS: ChemicalReaction[] = [
  {
    id: 'rx_cryo_water',
    reactantA: 'liquid_nitrogen',
    reactantB: 'water',
    resultA: 'smoke',
    resultB: 'snow',
    chance: 0.9,
    heatDelta: -120,
    pressureDelta: 1,
    effect: 'dissolve',
    description: 'Liquid nitrogen instantly flash-freezes water into ice and snow.',
  },
  {
    id: 'rx_cryo_lava',
    reactantA: 'liquid_nitrogen',
    reactantB: 'lava',
    resultA: 'smoke',
    resultB: 'obsidian',
    chance: 0.85,
    heatDelta: -300,
    pressureDelta: 3,
    effect: 'flash',
    description: 'Liquid nitrogen quenches molten lava into hard volcanic obsidian.',
  },
  {
    id: 'rx_uranium_plasma',
    reactantA: 'uranium',
    reactantB: 'plasma',
    resultA: 'plasma',
    resultB: 'toxic_gas',
    chance: 0.7,
    heatDelta: 1200,
    pressureDelta: 9,
    effect: 'explode',
    description: 'Plasma triggers runaway nuclear fission chain reaction.',
  },
  {
    id: 'rx_uranium_spark',
    reactantA: 'uranium',
    reactantB: 'spark',
    resultA: 'plasma',
    resultB: 'spark',
    chance: 0.45,
    heatDelta: 800,
    pressureDelta: 8,
    effect: 'explode',
    description: 'Thermal spark triggers critical fissile fission burst.',
  },
];
