import { ChemicalReaction } from '../types';

export const LIFE_REACTIONS: ChemicalReaction[] = [
  {
    id: 'rx_plant_water',
    reactantA: 'plant',
    reactantB: 'water',
    resultA: 'plant',
    resultB: 'plant',
    chance: 0.35,
    heatDelta: 0,
    pressureDelta: 0,
    effect: 'none',
    description: 'Foliage absorbs water to sprout new branches.',
  },
  {
    id: 'rx_seed_water',
    reactantA: 'seed',
    reactantB: 'water',
    resultA: 'plant',
    resultB: 'plant',
    chance: 0.7,
    heatDelta: 5,
    pressureDelta: 0,
    effect: 'spark',
    description: 'Seed germinates rapidly in contact with water.',
  },
  {
    id: 'rx_fungus_wood',
    reactantA: 'fungus',
    reactantB: 'wood',
    resultA: 'fungus',
    resultB: 'fungus',
    chance: 0.2,
    heatDelta: 2,
    pressureDelta: 0,
    effect: 'none',
    description: 'Fungi decompose dead wood into mycelium.',
  },
  {
    id: 'rx_fungus_plant',
    reactantA: 'fungus',
    reactantB: 'plant',
    resultA: 'fungus',
    resultB: 'fungus',
    chance: 0.25,
    heatDelta: 2,
    pressureDelta: 0,
    effect: 'none',
    description: 'Fungal blight colonizes living plants.',
  },
];
