import { ChemicalReaction } from '../types';

export const WATER_REACTIONS: ChemicalReaction[] = [
  {
    id: 'rx_water_fire',
    reactantA: 'water',
    reactantB: 'fire',
    resultA: 'steam',
    resultB: null,
    chance: 0.9,
    heatDelta: -40,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Water extinguishes fire and turns into rising steam vapor.',
  },
  {
    id: 'rx_water_lava',
    reactantA: 'water',
    reactantB: 'lava',
    resultA: 'steam',
    resultB: 'stone',
    chance: 0.85,
    heatDelta: 120,
    pressureDelta: 3,
    effect: 'flash',
    description: 'Water rapidly chills molten lava into solid rock while flash-boiling into steam.',
  },
  {
    id: 'rx_water_salt',
    reactantA: 'water',
    reactantB: 'salt',
    resultA: 'salt_water',
    resultB: null,
    chance: 0.6,
    heatDelta: -5,
    pressureDelta: 0,
    effect: 'none',
    description: 'Salt dissolves into water, creating conductive salt brine.',
  },
  {
    id: 'rx_elec_water',
    reactantA: 'electricity',
    reactantB: 'water',
    resultA: 'hydrogen',
    resultB: 'oxygen',
    chance: 0.45,
    heatDelta: 25,
    pressureDelta: 1,
    effect: 'spark',
    description: 'Electrolysis splits liquid water into gaseous hydrogen and oxygen.',
  },
  {
    id: 'rx_elec_saltwater',
    reactantA: 'electricity',
    reactantB: 'salt_water',
    resultA: 'hydrogen',
    resultB: 'toxic_gas',
    chance: 0.7,
    heatDelta: 40,
    pressureDelta: 2,
    effect: 'spark',
    description: 'Electrolysis of salt brine releases hydrogen and chlorine gas.',
  },
];
